server:
  port: 8080

eureka:
  instance:
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    instance:
      preferIpAddress: true

spring:
  application:
    name: sgq-api-gateway
  cloud:
    gateway:
      routes:
        - id: SGQ-QUALITY-COMPLIANCE
          uri: lb://SGQ-QUALITY-COMPLIANCE
#          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
  main:
    web-application-type: reactive