server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    instance:
      preferIpAddress: true

spring:
  application:
    name: sgq-api-gateway
  cloud:
    gateway:
      routes:

        - id: sgq-quality-compliance
          uri: http://sgq-quality-compliance:8081
          predicates:
            - Path=/compliance/api/v1/**

        - id: sgq-quality-transparence
          uri: http://sgq-quality-transparence:8082
          predicates:
            - Path=/notification/api/v1/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  main:
    web-application-type: reactive